name: build

on:
  workflow_call:
  push:
    branches:
      - main
  pull_request:
    branches: [main]

permissions:
  contents: read
  packages: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.19.0
        with:
          java-distribution: graalvm
          java-version: 25
          maven-version: 3.9.11
          cache-enabled: true

      - name: Maven build
        run: mvn --batch-mode --update-snapshots verify
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Maven build native
        run: mvn --batch-mode --update-snapshots verify -Dnative
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
